
bash lfs_batch_jobs/simple_mul.sh
bash lfs_batch_jobs/function_task_static.sh
bash lfs_batch_jobs/function_task_static_mul_hidden_size.sh
#bash lfs_batch_jobs/function_task_static_regualization.sh
bash lfs_batch_jobs/function_task_static_mul_input_size.sh
bash lfs_batch_jobs/function_task_static_mul_overlap.sh
bash lfs_batch_jobs/function_task_static_mul_range.sh
# bash lfs_batch_jobs/function_task_static_ablation.sh
# bash lfs_batch_jobs/function_task_static_mul_hidden_size_ablation.sh
bash lfs_batch_jobs/function_task_static_mul_subset.sh

# bash lfs_batch_jobs/sequential_mnist_prod_long.sh
# bash lfs_batch_jobs/sequential_mnist_prod_reference.sh
