
from .simple_function_static import SimpleFunctionStaticNetwork
from .simple_function_recurrent import SimpleFunctionRecurrentNetwork
from .sequential_svhn import SequentialSvhnNetwork
from .sequential_mnist import SequentialMnistNetwork
from .regression_mnist import RegressionMnistNetwork
from .number_translation import NumberTranslationNetwork