
from .simple_function_static import SimpleFunctionStaticNetwork
from .simple_function_recurrent import SimpleFunctionRecurrentNetwork
from .sequential_mnist import SequentialMnistNetwork
from .regression_mnist import RegressionMnisNetwork
from .number_translation import NumberTranslationNetwork